services:
    api:
        build:
            context: .
            network: host
        container_name: ff7-for-st-jude-api
        network_mode: host
        env_file:
            - .env
        restart: always
